### PR TITLE
update failing links to new urls

### PR DESCRIPTION
**Pull request by shimwell**
I was just running the nice depletion/generate_endf71_chain.py script and got a 404 url not found error

so I went to the website and it looks like all the links have changed slightly.

I've been through and updated the links in a few places to get them working again

### CODE REVIEW

**Comment by shimwell** [comment]
Marking as draft as I need to go through and check these one more time.

**Comment by AnderGray** [comment]
`generate_endf71_chain_casl.py` working, but `generate_tendl_chain.py` gives error:

```
Downloading tendl-download/TENDL-n.tgz... 2986500080  [100.00%]
Extracting tendl-download/TENDL-n.tgz...
Traceback (most recent call last):
  File "./generate_tendl_chain.py", line 117, in <module>
    main()
  File "./generate_tendl_chain.py", line 81, in main
    with open('tendl2019_nuclides.json', 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'tendl2019_nuclides.json'
```

**Comment by shimwell** [comment]
> 

Looks like the hashlib.md5 for the JEFF files have changed.

**Comment by shimwell** [comment]
Both of these errors appear unrelated to the updating of the endf URL. Shall I fix them in a separate PR or is it best to do the fixes here.

**Comment by AnderGray** [comment]
In my opinion - stick the changes here

**Review by paulromano — APPROVED** [review]
These changes look good to me. I'll submit a separate fix for the JEFF 3.3 issue.

**Pull request merged**
