### PR TITLE
Update JEFF 3.3 conversion script and add generation script

### PR DESCRIPTION
**Pull request by paulromano**
The original ACE data distributed by OECD/NEA for JEFF 3.3 only contained a single temperature. The current [distribution](https://www.oecd-nea.org/dbdata/jeff/jeff33/index.html) now contains neutron data at 293, 600, 900, 1200, 1500, and 1800 K.

### CODE REVIEW

**Comment by paulromano** [comment]
I also just added a `generate_jeff33.py` script that runs NJOY to generate ACE files which then get converted to HDF5 files.

**Comment by Shimwell** [comment]
I guess another option is to instead of getting the convert Jeff script to use tendl data the isotopes that don't convert with NJOY could be skipped by the script. Then users could use the combine libaries script to fill in the missing isotopes with the library of there choice. I suppose it depends on how many are not converting with NJOY but just a thought.

**Comment by paulromano** [comment]
@Shimwell The convert script goes through fine because it is only dealing with pre-existing ACE files. The generation script didn't work for C13 and O17 because errors in the evaluation cause NJOY to abort. These two isotopes in particular come from TENDL-2015, so it seemed prudent to replace them with a newer version of TENDL.

**Comment by Shimwell** [comment]
Is it worth putting in the same option we have in the convert_jeff32.py script to allow temperatures to be selected
https://github.com/openmc-dev/data/blob/fb93e4efd8eb4ade7f8c9e53fc5932637f8114ff/convert_jeff32.py#L46-L51

**Comment by paulromano** [comment]
@Shimwell Sorry it took me a while to get back to this. I just updated this branch with an option to specify the temperatures on the command line

**Review by Shimwell — APPROVED** [review]

**Comment by Shimwell** [comment]
Looks find to me, the only tiny tiny reservation I had was the use of Tendl 19 as I think that technically stops the download being called Jeff 3.3. I was half thinking we should opt to not use broken cross section files and leave it without those files. Then users can use the combine_libraries.py if gaps need filling in, they will be more aware of of the substitutes. But I think the solution you have makes it much easier for the user, so I think you have got the best compromise there.

**Pull request merged**
