### PR TITLE
Add TENDL depletion chain generation script (and two others)

### PR DESCRIPTION
**Pull request by paulromano**
This PR adds a script to generate a depletion chain based on neutron data in TENDL 2019. While TENDL 2019 actually includes incident neutron data for 2812 nuclides (!), they distribute ACE files for 630 of those nuclides. This script uses that set of 630 nuclides as the basis for choosing what reactions can result in transmutation (this also impacts what nuclides are added to a model for depletion purposes). TENDL doesn't actually include decay or fission product yield sublibraries, so those need to be provided from elsewhere. The script has a flag that allows one to select either JEFF 3.3 or ENDF/B-VIII.0 for providing decay/FPY data (with JEFF 3.3 as the default).

Because the TENDL depletion chain is intended primarily for fusion applications, all potential transmutation reactions are included in the depletion chain rather than the traditional 7 that we normally include ((n,2n), (n,3n), (n,4n), (n,gamma), (n,p), (n,a), and fission) for fission applications. I would also note that there are multiple versions of TENDL that differ in their maximum energy. The default (S30) library goes up to 30 MeV and includes reactions up to MT=117. There is an S60 library that goes up to 60 MeV and includes many more exotic reactions with MT > 117.

Two other small scripts that are part of this PR:
- `add_branching_ratios.py` -- allows you to take an existing depletion chain and add branching ratios to it from one of the JSON files present
- `reduce_chain.py` -- a script for using the `Chain.reduce` method to minimize the number of nuclides present in the chain using all stable/long-lived nuclides as a starting point

### CODE REVIEW

**Comment by AI-Pranto** [comment]
@paulromano Looks like, It can't find the complete list of transmutation reactions in `openmc.deplete.chain.REACTIONS`.
```
Traceback (most recent call last):
  File "generate_tendl_chain.py", line 117, in <module>
    main()
  File "generate_tendl_chain.py", line 111, in main
    reactions=dep.chain.REACTIONS.keys()
AttributeError: module 'openmc.deplete.chain' has no attribute 'REACTIONS'
```

**Comment by paulromano** [comment]
@AI-Pranto This script relies on a recent addition to OpenMC (see [this PR](https://github.com/openmc-dev/openmc/pull/1618)). If you run this script based on the `develop` branch of OpenMC, it should work fine.

**Comment by AI-Pranto** [comment]
My bad :( 
I was running  two scripts  simultaneously on `openmc-0.12`  and `openmc-dev` branch. Thanks @paulromano

**Comment by Shimwell** [comment]
Sorry totally forgot about this, testing and reviewing now

**Review by Shimwell — APPROVED** [review]

**Comment by Shimwell** [comment]
All works over here

**Pull request merged**
