### PR TITLE
Add JENDL-5 library

### PR DESCRIPTION
**Pull request by AI-Pranto**
Added option to convert JENDL-5 neutron data released on December 27, 2021

### CODE REVIEW

**Comment by shimwell** [comment]
Looks like a nice straight forward addition.

I can test this script runs and downloads the data.

**Comment by shimwell** [comment]
I did start running this script yesterday but it does take a long time (endf processing) so I'm retrying on a computer with more cores this evening. Sorry for the delay

**Comment by shimwell** [comment]
The download and processing script runs over here.

NJOY writes a few messages out to the screen during this script.

```
/home/jshim/data-alpranto/jendl-5.0-endf/jendl5-n/n_092-U-235.dat Command 'njoy' returned non-zero exit status 2.
/home/jshim/data-alpranto/jendl-5.0-endf/jendl5-n/n_084-Po-210.dat Command 'njoy' returned non-zero exit status 77.
/home/jshim/data-alpranto/jendl-5.0-endf/jendl5-n/n_084-Po-209.dat Command 'njoy' returned non-zero exit status 77.
/home/jshim/data-alpranto/jendl-5.0-endf/jendl5-n/n_083-Bi-208.dat Command 'njoy' returned non-zero exit status 77.
/home/jshim/data-alpranto/jendl-5.0-endf/jendl5-n/n_083-Bi-207.dat Command 'njoy' returned non-zero exit status 77.
```

I've not checked the h5 files in simulations.

**Comment by paulromano** [comment]
@AI-Pranto I haven't, but I did run a few of the nuclides with `IncidentNeutron.from_njoy(..., stdout=True)` to see what errors were produced and there were a variety of errors

**Comment by AI-Pranto** [comment]
For some nuclides (e.g. N-14, N-15, U-235), I got following error message when I call njoy using `IncidentNeutron.from_njoy()`
```bash
Error termination. Backtrace:
#0  0x7f957f82ed21 in ???
#1  0x7f957f82f869 in ???
#2  0x7f957f83054f in ???
#3  0x7f957fa70e20 in ???
#4  0x7f957fa755b4 in ???
#5  0x7f957fa76a2b in ???
#6  0x55b0830a5d4f in tablio
	at /home/pranto/Desktop/njoy_test/NJOY2016/src/endf.f90:1002
#7  0x55b0830afb48 in __endf_MOD_tab1io
	at /home/pranto/Desktop/njoy_test/NJOY2016/src/endf.f90:258
#8  0x55b0831fc83a in sixbar
	at /home/pranto/Desktop/njoy_test/NJOY2016/src/heatr.f90:2789
#9  0x55b08320838f in nheat
	at /home/pranto/Desktop/njoy_test/NJOY2016/src/heatr.f90:1653
#10  0x55b083215f54 in __heatm_MOD_heatr
	at /home/pranto/Desktop/njoy_test/NJOY2016/src/heatr.f90:375
#11  0x55b08301587c in njoy
	at /home/pranto/Desktop/njoy_test/NJOY2016/src/main.f90:205
#12  0x55b083015aea in main
	at /home/pranto/Desktop/njoy_test/NJOY2016/src/main.f90:112
```
but running njoy directly didn't produce those error messages at all. Is there any reason why we are getting error message in the first place, @paulromano?

**Comment by paulromano** [comment]
FYI: https://github.com/njoy/NJOY2016/issues/228

**Comment by whaeck** [comment]
@paulromano Can you check that the fix/nxcmax-v2 branch on NJOY2016 fixes these processing isssues. If there are any remaining issues, can you give me a list of nuclides and associated input files?

Thanks!

**Comment by paulromano** [comment]
@whaeck will do!

**Comment by paulromano** [comment]
@whaeck I'm still seeing a lot of failures (working on getting the inputs and will attach once I have them):
```
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_007-N-014.dat Command 'njoy' returned non-zero exit status 2.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_007-N-015.dat Command 'njoy' returned non-zero exit status 2.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_009-F-019.dat Command 'njoy' returned non-zero exit status 2.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_013-Al-027.dat Command 'njoy' returned non-zero exit status 2.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_025-Mn-055.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_030-Zn-068.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_030-Zn-066.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_030-Zn-064.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_030-Zn-067.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_038-Sr-084.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_038-Sr-088.dat Command 'njoy' died with <Signals.SIGSEGV: 11>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_038-Sr-086.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_038-Sr-087.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_041-Nb-091.dat Command 'njoy' died with <Signals.SIGSEGV: 11>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_043-Tc-099.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_050-Sn-112.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_050-Sn-118.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_052-Te-120.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_052-Te-121m1.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_052-Te-123.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_052-Te-122.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_052-Te-127m1.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_052-Te-129m1.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_052-Te-125.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_052-Te-130.dat Command 'njoy' died with <Signals.SIGSEGV: 11>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_052-Te-131m1.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_052-Te-128.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_052-Te-126.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_052-Te-124.dat Command 'njoy' died with <Signals.SIGSEGV: 11>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_053-I-131.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_053-I-130.dat Command 'njoy' died with <Signals.SIGSEGV: 11>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_053-I-128.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_053-I-129.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_053-I-127.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_055-Cs-133.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_058-Ce-136.dat Command 'njoy' died with <Signals.SIGSEGV: 11>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_058-Ce-138.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_060-Nd-142.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_063-Eu-153.dat Command 'njoy' died with <Signals.SIGSEGV: 11>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_063-Eu-151.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_064-Gd-157.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_064-Gd-155.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_073-Ta-179.dat Command 'njoy' died with <Signals.SIGSEGV: 11>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_073-Ta-182.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_074-W-180.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_073-Ta-180m1.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_074-W-182.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_074-W-183.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_073-Ta-181.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_076-Os-184.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_076-Os-189.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_076-Os-186.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_076-Os-188.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_076-Os-187.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_078-Pt-189.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_078-Pt-190.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_078-Pt-191.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_078-Pt-193.dat Command 'njoy' died with <Signals.SIGSEGV: 11>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_078-Pt-196.dat Command 'njoy' died with <Signals.SIGSEGV: 11>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_078-Pt-194.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_078-Pt-195.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_078-Pt-192.dat Command 'njoy' died with <Signals.SIGSEGV: 11>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_080-Hg-195.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_080-Hg-197.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_080-Hg-196.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_080-Hg-198.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_080-Hg-199.dat Command 'njoy' died with <Signals.SIGSEGV: 11>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_080-Hg-200.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_081-Tl-204.dat Command 'njoy' died with <Signals.SIGABRT: 6>.
/home/romano/openmc-data/jendl-5.0-endf/jendl5-n/n_092-U-235.dat Command 'njoy' returned non-zero exit status 2.
```
Here are some sample outputs corresponding to each type of error. For the "non-zero exit status 2" (N14):
```
 njoy 2016.67  xxXxx22                                       03/11/22 06:25:15
 *****************************************************************************

 reconr...                                                                0.0s

 broadr...                                                                0.3s

 heatr...                                                                 0.4s

 ---message from hinit---mf6, mt 16 does not give recoil za= 13026
                          one-particle recoil approx. used.

 ---message from hinit---mf6, mt 22 does not give recoil za= 13027
                          one-particle recoil approx. used.

 ---message from hinit---mf6, mt 28 does not give recoil za= 13027
                          one-particle recoil approx. used.

 ---message from hinit---mf6, mt 91 does not give recoil za= 13027
                          one-particle recoil approx. used.

 ---message from hinit---mf6, mt203 does not give recoil za= 12027
                          one-particle recoil approx. used.

 ---message from hinit---mf6, mt207 does not give recoil za= 11024
                          one-particle recoil approx. used.

 ---message from sixbar---no distribution for mt  5 particle     0
At line 1002 of file /home/romano/codes/NJOY2016/src/endf.f90 (unit = 14, file = '/tmp/gfortrantmpf1OyDg')
Fortran runtime error: Bad value during integer read

Error termination. Backtrace:
#0  0x146b5b8f7d5a
#1  0x146b5b8f8869
#2  0x146b5b8f954f
#3  0x146b5bb39e20
#4  0x146b5bb3e5b4
#5  0x146b5bb3fa2b
#6  0x146b5bcbc0d6
#7  0x146b5bcc6280
#8  0x146b5bd6a4ab
#9  0x146b5bd6cc30
#10  0x5559d3054754
#11  0x5559d30542ce
#12  0x146b5b7090b2
#13  0x5559d305430d
#14  0xffffffffffffffff
```

For "died with <Signals.SIGABRT: 6>" (Mn55):
```
...
 purr...                                                                 17.8s

 mat = 2525                                                              17.8s
double free or corruption (!prev)

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x1474ee247d5a
#1  0x1474ee246ef5
#2  0x1474ee0780bf
#3  0x1474ee07803b
#4  0x1474ee057858
#5  0x1474ee0c229d
#6  0x1474ee0ca32b
#7  0x1474ee0cbfdb
#8  0x1474ee729998
#9  0x55b120c856e4
#10  0x55b120c852ce
#11  0x1474ee0590b2
#12  0x55b120c8530d
#13  0xffffffffffffffff
```

For "died with <Signals.SIGSEGV: 11>" (Sr88):
```
 purr...                                                                 17.2s

 mat = 3837                                                              17.2s

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x1456d3e25d5a
#1  0x1456d3e24ef5
#2  0x1456d3c560bf
#3  0x1456d40794b3
#4  0x1456d407951b
#5  0x1456d406aea5
#6  0x1456d40679db
#7  0x1456d406c964
#8  0x1456d406da2b
#9  0x1456d406a63b
#10  0x1456d41eea85
#11  0x1456d4307367
#12  0x5595827696e4
#13  0x5595827692ce
#14  0x1456d3c370b2
#15  0x55958276930d
#16  0xffffffffffffffff
```

**Comment by paulromano** [comment]
@whaeck here are the inputs:
https://anl.box.com/s/ketichdptahd9jgcb4xawq3t9o7z3gb3

**Comment by whaeck** [comment]
Thanks. I downloaded them and I will start going through them to see what is going on.

**Comment by whaeck** [comment]
@paulromano You can try again with the latest NJOY2016 update available in the develop branch. The PURR issues stem from an array size, similar to the ACER one so that one was simple to fix.

The N14, N15, F19 and Al27 issues come from what I consider an evaluation error. In all these cases, the MF3 data goes up to 200 MeV while the MF13 data only goes up to 20 MeV. As a result, the unionised energy grid goes only to 20 MeV and that gets you in trouble in HEATR. This can be fixed easily by adding a (2e+7, 0.0) and (2e+8, 0.) point in the MF13 MT3 section (I tried it on N14, it processes after this change). I believe this is an oversight on the part of the evaluators.

I haven't looked at the U235 issue yet (it could be a similar issue as the 4 nuclides mentioned above). I will look at this further tomorrow.

**Comment by paulromano** [comment]
Thanks @whaeck. Appreciate you tracking down the bugs! I'll give it another try and see how things go this time.

**Comment by paulromano** [comment]
@whaeck I've confirmed that everything is fixed now except for N14, N15, F19, Al27, and U235 as you said. Let me know what you figure out for U235. For the others with evaluation bugs, we (OpenMC) will probably just have to implement patches here as part of our data processing scripts.

**Comment by paulromano** [comment]
I tried this running the generate_jendl.py script with JENDL-5 and now it looks like most nuclides go through fine _except_ for N14, N15, F19, and Al27. As @whaeck pointed out, this is actually due to errors in the evaluations. Those errors have been fixed in an [errata](https://wwwndc.jaea.go.jp/jendl/j5/JENDL-5_Errata.html) (update-6), so we'll need to download the corrected files in order to process the full library.

**Comment by paulromano** [comment]
@AI-Pranto Thanks for the updates. However, now when I try to run the script I'm getting a syntax error.

**Comment by AI-Pranto** [comment]
@paulromano, sorry for taking so long to get back to you. I've run the script for the added release and was able to process all files.

**Review by paulromano — APPROVED** [review]
Sorry for the long delay in having another look @AI-Pranto. Everything seems to be running well now. Thanks again!

**Pull request merged**
